name: GitHub-Profile-3D-Contrib

on:
  schedule:  # This will run once a day at 18:00 UTC (03:00 JST).
    - cron: "0 18 * * *"
  workflow_dispatch:  # Allow manual triggering of the workflow.

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # Step 1: Check out the code in the repository
      - uses: actions/checkout@v3
      
      # Step 2: Use the yoshi389111/github-profile-3d-contrib action
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub Token stored in secrets
          USERNAME: ${{ github.repository_owner }}  # Use the repository owner's username

      # Step 3: Commit and push the generated 3D profile image to the repository
      - name: Commit & Push
        run: |
          git config user.name "github-actions"  
          git config user.email "github-actions@github.com"
          git pull origin main --rebase  # Fetch and rebase remote changes
          git add -A .
          git commit -m "generated 3D profile image"
          git push
