name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          TOKEN: ${{ secrets.TOKEN }}  # Ensure this is set in your repository secrets
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main --rebase
          git add -A
          git commit -m "generated" || echo "No changes to commit"
          git push origin main